config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :feedbacks
  resources :announcements
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations      => "users/registrations",
                                       :sessions           => "users/sessions",
                                       :passwords         => "users/passwords",
                                       :admins            => "users/admins"
                                      }
  

  get "/regolamento", to: "home#regolamento"
  
  root 'home#presentazione'
  get '/profilo', to: 'home#profilo_utente'
  get '/cerca' => 'home#risultati_ricerca'
  get '/cerca_categorie', to: 'home#risultati_ricerca_categorie'
  get '/richieste_inviate', to: 'bookings#richieste_inviate'
  get '/chiudi_richiesta', to: 'bookings#chiudi_annuncio'
  get '/messaggi_inviati', to: 'messages#messaggi_inviati'
  get '/segnala_annuncio', to: 'announcements#segnala_annuncio'
  get '/miostorico',to: 'announcements#storico_oggetti_regalati'
  
  
  
  
  get "/listaUtenti", to: 'users/admins#listaUtenti'
  get "/listaAnnunci", to: 'users/admins#listaAnnunci'
  get "/faiAdmin", to: 'users/admins#faiAdmin'
  get "/modificaUtente_show", to: 'users/admins#modificaUtente_show'
  post "/modificaUtente_update", to: 'users/admins#modificaUtente_update'
  get "/annunciSegnalati", to: 'users/admins#annunciSegnalati'
  get "/togliSegnalato", to: 'users/admins#togliSegnalato'
  get "/modificaAnnuncio_show", to: 'users/admins#modificaAnnuncio_show'
  post "/modificaAnnuncio_update", to: 'users/admins#modificaAnnuncio_update'
  get "/chiudiAnnuncio", to: 'users/admins#chiudiAnnuncio'
  get "/apriAnnuncio", to: 'users/admins#apriAnnuncio'
  get "/listaPrenotazioni", to: "users/admins#listaPrenotazioni"
  
  get "/banna_show", to: "users/admins#banna_show"
  post "/banna_action", to: "users/admins#banna_action"
  get "/togliBan", to: "users/admins#togliBan"
  get "/errori", to: 'home#errori'
  
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
    belongs_to :user
    has_one :booking
	validates :titolo, :presence => true
	validates :descrizione, :presence => true
	validates :categoria, :presence => true
	
	geocoded_by :luogo
	after_validation :geocode
	
	def nome_creatore
		User.where("id = ?", id_proprietario_id).take.nome
	end
	
	def id_creatore
		User.where("id = ?", id_proprietario_id).take.id
	end
	
	def prendi_booking
		@booking = Booking.where(annuncio_id: id).take
	end
	
	def prenotato_da
		@join = User.joins("INNER JOIN bookings ON bookings.prenotato_id = users.id ").where("annuncio_id = ?", id).take
		if @join
			@join = @join.nome
		else
			""
		end
	end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  Numero_risultati_per_pagina = 20
  
  # GET /announcements
  # GET /announcements.json
  def index
    #Solo gli annunci del proprietario e aperti vengono visualizzati.
    @announcements = current_user.oggetti_del_proprietario.paginate(page: params[:page],per_page: Numero_risultati_per_pagina)
    render layout: "per_annunci"
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])
    Announcement.where("id = ?",@announcement.id).limit(1).update_all("visite = #{@announcement.visite+1}")
    render layout: "per_annunci"
  end
  
  def segnala_annuncio
    @announcement = Announcement.find(params[:id])
    Announcement.where("id = ?",@announcement.id).limit(1).update_all("segnalato = 1")
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Annuncio segnalato!' }
      format.json { head :no_content }
    end
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    render layout: "per_annunci"
  end

  # GET /announcements/1/edit
  def edit
    #Solo i proprietario degli annunci possono, modificare l'annuncio.
    if(current_user.id == @announcement.id_proprietario_id)
      render layout: "per_annunci"
    else
      redirect_to root_path
    end
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @user = current_user
    @announcement = Announcement.new(params[:announcement].permit(:titolo, :descrizione, :categoria, :foto, :etichetta, :segnalato, :visite, :id_proprietario_id, :luogo))
    @announcement.id_proprietario_id = @user.id
    uploaded_io = params[:announcement][:foto]
    if uploaded_io != nil
      puts "====================================================="
      Rails.logger.debug "#{@announcement.inspect}"
      puts "====================================================="
      estensione = uploaded_io.original_filename.split('.')[-1]
      File.open(Rails.root.join('app','assets','images','foto_annunci', "annuncio#{Announcement.last.id+1}.#{estensione}"), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      @announcement.foto = "foto_annunci/annuncio#{Announcement.last.id+1}.#{estensione}"
    end
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement}
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    uploaded_io = params[:announcement][:foto]
        if uploaded_io != nil
            #Rails.logger.debug "#{params[:announcement].inspect}"
            if @announcement.foto != "" and @announcement.foto != nil
              file_veccchio = @announcement.foto.split('/')[-1]
              if File.exist?(Rails.root.join('app','assets','images','foto_annunci', "#{file_veccchio}"))
                File.delete(Rails.root.join('app','assets','images','foto_annunci', "#{file_veccchio}"))
              end
            end
            estensione = uploaded_io.original_filename.split('.')[-1]
            File.open(Rails.root.join('app','assets','images','foto_annunci', "annuncio#{@announcement.id}.#{estensione}"), 'wb') do |file|
                file.write(uploaded_io.read)
            end
            params[:announcement][:foto] = "foto_annunci/annuncio#{@announcement.id}.#{estensione}"
            #Rails.logger.debug "#{params[:announcement].inspect}"
        end
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Annuncio aggiornato!' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    #Se l'annuncio è prenotato, elimino anche la sua annessa prenotazione.
    if(@announcement.prendi_booking != nil) 
      @booking = @announcement.prendi_booking
      @booking.destroy
    end
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Annuncio cancellato!' }
      format.json { head :no_content }
    end
  end
  
  def storico_oggetti_regalati
      @announcements=(current_user.storico_oggetti_regalati).paginate(page: params[:page],per_page: Numero_risultati_per_pagina)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:titolo, :descrizione, :categoria, :foto, :etichetta, :segnalato, :visite, :id_proprietario, :luogo)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<style>
      .map {
        height: 300px;
      }
      .controls {
        background-color: #fff;
        border-radius: 2px;
        border: 1px solid transparent;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        box-sizing: border-box;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        height: 29px;
        margin-left: 17px;
        margin-top: 10px;
        outline: none;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
      }

      .controls:focus {
        border-color: #4d90fe;
      }
</style>
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <center>
          <table width="100%" border="1">
            <tr>
              <td colspan="1"><%= f.label "Titolo:" %></td>
              <td colspan="1"><%= f.text_field :titolo, :required => true %></td>
               <td style="width: 50%;" rowspan="8" valign="top" id="map">
              </td>
            </tr>
            <tr>
              <td colspan="1"><%= f.label "Categoria:" %></td>
              <td colspan="1"><%= f.select :categoria, ['Auto','Accessori auto',
                                  'Moto', 'Accessori moto',
                                  'Attrezzature da lavoro', 'Informatica',
                                  'Fotografia', 'Audio/video',
                                  'Videogiochi', 'Telefonia',
                                  'Mobili', 'Casalinghi',
                                  'Elettrodomestici', 'Abbigliamento',
                                  'Giardinaggio', 'Tutto per bambini',
                                  'Animali', 'Cancelleria',
                                  'Sport', 'Collezionismo'], include_blank: false %>
</td>
            </tr>
            <tr>
              <td colspan="1"><%= f.label "Foto:" %></td>
              <td colspan="1"><%= f.file_field :foto, accept: 'image/png,image/gif,image/jpeg' %></td>
            </tr>
            <tr>
              <td><%= f.label "Luogo:" %></td>
              <td><%= f.text_field :luogo, :required => true %> </td>
            </tr>
            <tr>
              <td colspan="2"><%= f.label "Descrizione:" %></td>
            </tr>
            <tr>
              <td colspan="2"><%= f.text_area :descrizione, :rows => 10, style: 'width:100%;', :required => true %></td>
            </tr>
            
            
            <tr><td colspan="2">&nbsp;</td></tr>
            <tr>
              <td colspan="2" align="center"><%= f.submit "Invia" %> || <%= button_tag "Reset", type: :reset %></td>
            </tr>
          </table>
          </center>
<% end %>

<script>
      function initMap() {
        //Posizione di default della mappa
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 41.8919, lng: 12.5113},
          zoom: 13
        });
        
        //Campo di input
        var input = document.getElementById('announcement_luogo');

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            return;
          }

          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }

          // Imposto la posizione sulla mappa della destinazione cercata
          marker.setPlace({
            placeId: place.place_id,
            location: place.geometry.location
          });
          marker.setVisible(true);

          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.formatted_address);
          document.getElementById('announcement_luogo').value = place.formatted_address;
          infowindow.open(map, marker);
        });
      }
    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBIKW0xq45fu2dqUZtBMqXps0SrSHJu0c&libraries=places&callback=initMap"async defer></script>

app/views/announcements/_mappa.html.erb
<style>
      #map {
        height: 300px;
      }
      #controls {
        background-color: #fff;
        border-radius: 2px;
        border: 1px solid transparent;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        box-sizing: border-box;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        height: 29px;
        margin-left: 17px;
        margin-top: 10px;
        outline: none;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
      }

      .controls:focus {
        border-color: #4d90fe;
      }
</style>

<table height="100%" width="100%" border="1">
	<td style="width: 50%;" rowspan="8" valign="top" id="map">Sto caricando</td>
</table>


<script>
		var vlat = <% if @announcement.latitude == nil %> 41.8919 <% else %> <%= @announcement.latitude %> <% end %>;
		var vlng = <% if @announcement.longitude == nil %> 41.8919 <% else %> <%= @announcement.longitude %> <% end %>;
      function initMap() {
        //Posizione di default della mappa
        map = new google.maps.Map(document.getElementById('map'), {
				center: {
					lat: vlat,
					lng: vlng
				},
				zoom: 12
			});
			var marker = new google.maps.Marker({
				position: {
					lat: vlat,
					lng: vlng
				},
				map: map,
				title: 'Posizione attuale'
			});
			marker.setMap(map);
		
        
        //Campo di input
        var input = document.getElementById('announcement_luogo');

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            return;
          }

          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }

          // Imposto la posizione sulla mappa della destinazione cercata
          marker.setPlace({
            placeId: place.place_id,
            location: place.geometry.location
          });
          marker.setVisible(true);

          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.formatted_address);
          document.getElementById('announcement_luogo').value = place.formatted_address;
          infowindow.open(map, marker);
        });
      }
    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBIKW0xq45fu2dqUZtBMqXps0SrSHJu0c&libraries=places&callback=initMap"async defer></script>

app/views/announcements/edit.html.erb
<!-- <h2>Modifica annuncio</h2>
</section>
<%= link_to 'Mostra', @announcement %> |
<%= link_to 'Indietro', announcements_path %> -->




<section class="main-content">			
	<div class="row">
					<div class="span6">					
						<h4 class="title"><span class="text"><strong>Modifica</strong> annuncio</span></h4>


  <%= form_for(@announcement, html: {class: "form-stacked"}) do |f| %>
    <% if @announcement.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
  
        <ul>
        <% @announcement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <fieldset>
      <div class="control-group">
				<%= f.label "Titolo", class:"control-label" %>
			  <div class="controls">
			    <%= f.text_field :titolo, class:"input-xlarge", :required => true %>
			  </div>
			</div>
			<div class="control-group">
				<%= f.label "Categoria", class:"control-label" %>
			  <div class="controls">
			    <%= f.select :categoria, ['Auto','Accessori auto',
                                    'Moto', 'Accessori moto',
                                    'Attrezzature da lavoro', 'Informatica',
                                    'Fotografia', 'Audio/video',
                                    'Videogiochi', 'Telefonia',
                                    'Mobili', 'Casalinghi',
                                    'Elettrodomestici', 'Abbigliamento',
                                    'Giardinaggio', 'Tutto per bambini',
                                    'Animali', 'Cancelleria',
                                    'Sport', 'Collezionismo'], include_blank: false,  class:"input-xlarge" %>
			  </div>
			</div>
			<div class="control-group">
			  
			  
			  <label class="control-label">Foto</label>
                <div class="btn btn-inverse input-group">
                  <label class="input-group-btn ">
                    <span>
                        Scegli la foto <%= f.file_field :foto, accept: 'image/png,image/gif,image/jpeg', style: "display: none;" %>
                    </span>
                  </label>
                  <input type="text" class="form-control" readonly>
                </div> 
			  
			</div>
			<div class="control-group">
				<%= f.label "Luogo", class:"control-label" %>
			  <div class="controls">
			    <%= f.text_field :luogo,class:"input-xlarge" %>
			  </div>
			</div>
			<div class="control-group">
				<%= f.label "Descrizione", class:"control-label" %>
			  <div class="controls">
			    <%= f.text_area :descrizione, :rows => 5, style: 'width:90%;',class:"control-label", :required => true %>
			  </div>
			</div>
			<div class="actions">
			  <%= f.submit "Invia",tabindex:"9", class:"btn btn-inverse large", type:"submit", value:"Modifica annuncio" %> || 
			  <%= button_tag "Reset", tabindex:"9", class:"btn btn-inverse large", type: :reset, value:"Reset" %>
			</div>
    </fieldset>
    
  <% end %>

					</div>
				<div class="span6">
					<h4 class="title"><span class="text"><strong>Foto</strong></span></h4>
					<%= link_to image_tag("#{@announcement.foto}", :alt => 'PRODOTTO'), image_path("#{@announcement.foto}"), class:"thumbnail_p", "data-fancybox-group" => "group1", :title => "#{@announcement.titolo}", "data-turbolinks" =>"false" %>
        </div>
      </div>
  <div class="row">
			<div class="span12">
					<h4 class="title"><span class="text"><strong>MAPPA</strong></span></h4>
    			<table height="90%" width="100%" class="controlss" style="margin-bottom: 10px;">
            <td valign="top" id="map" ><%= image_tag("map-loader.gif") %></td>
          </table>
        </div>
      </div>
	</div>
</section>
			
<script>
		var vlat = <% if @announcement.latitude == nil %> 41.8919 <% else %> <%= @announcement.latitude %> <% end %>;
		var vlng = <% if @announcement.longitude == nil %> 41.8919 <% else %> <%= @announcement.longitude %> <% end %>;
      function initMap() {
        //Posizione di default della mappa
        map = new google.maps.Map(document.getElementById('map'), {
				center: {
					lat: vlat,
					lng: vlng
				},
				zoom: 12
			});
			var marker = new google.maps.Marker({
				position: {
					lat: vlat,
					lng: vlng
				},
				map: map,
				title: 'Posizione attuale'
			});
			marker.setMap(map);
		
        
        //Campo di input
        var input = document.getElementById('announcement_luogo');

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            return;
          }

          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }

          // Imposto la posizione sulla mappa della destinazione cercata
          marker.setPlace({
            placeId: place.place_id,
            location: place.geometry.location
          });
          marker.setVisible(true);

          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.formatted_address);
          document.getElementById('announcement_luogo').value = place.formatted_address;
          infowindow.open(map, marker);
        });
      }
    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBIKW0xq45fu2dqUZtBMqXps0SrSHJu0c&libraries=places&callback=initMap"async defer></script>


<script>
			$(function() {
				$('#myTab a:first').tab('show');
				$('#myTab a').click(function(e) {
					e.preventDefault();
					$(this).tab('show');
				})
			})
			$(document).ready(function() {
				$('.thumbnail_p').fancybox({
					openEffect: 'none',
					closeEffect: 'none'
				});

				$('#myCarousel-2').carousel({
					interval: 2500
				});
			});
		</script>
<script>
  $(function() {

  // We can attach the `fileselect` event to all file inputs on the page
  $(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  // We can watch for our custom `fileselect` event like this
  $(document).ready( function() {
      $(':file').on('fileselect', function(event, numFiles, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
  });
  
});
</script>

app/views/announcements/index.html.erb
			<center>
				<div class="page-header">
        	<h1>I tuoi annunci (<%= @announcements.count %>)</h1>
      	</div>
			</center>
			<section class="main-content">		
				<div class="row">						
					<div class="span12">								
						<ul class="thumbnails listing-products">
						
						<% if @announcements == nil %>
    				<section class="header_text sub">
							<h4><span>Non hai creato nessun annuncio </span></h4>
						</section>
						<% else %>
							<% @announcements.each do |announcement| %>
								<li class="span3">
									<div class="product-box">
										<span class="sale_tag"></span>												
											<% if (announcement.foto != "")  =%>
												<p><%= link_to image_tag("#{announcement.foto}", class: "foto_annunci_normalizzate"), announcement %></p>
											<% else %>
												<p><%= link_to image_tag("Temporanei/avatar"), announcement %></p>
											<% end %>
											<%= link_to announcement.titolo, announcement, class: "title" %><br/>
											<a class="category">[<%= announcement.categoria %>]</a></br>
											<%= link_to 'Modifica', edit_announcement_path(announcement), class: "category"%> | <%= link_to 'Elimina', announcement, method: :delete, data: { confirm: 'Sei sicuro?' }, class: "category" %></br>
											<a class="category"> 
												<% if announcement.prenotato_da != ""%>
													L'annuncio è stato prenotato da: <%= announcement.prenotato_da %>
												<% else %>
													L'annuncio è ancora disponibile
												<% end %>
											</a></br>
									</div>
								</li>
							<% end %>
						</ul>	
						<hr>
						<div class="pagination pagination-small pagination-centered">
							<%= will_paginate @announcements, :previous_label => 'Prec', :next_label => 'Succ', renderer: BootstrapPagination::Rails %>
						</div>
          <% end %>
					</div>
				</div>
			</section>

app/views/announcements/new.html.erb
<!-- <%= link_to 'Indietro', announcements_path %> -->

        <center><div class="page-header">
        	<h1>Aggiungi nuovo annuncio</h1>
      	</div></center>	

			<section class="main-content">				
				<div class="row">
					<div class="span6">					
						<h4 class="title"><span class="text"><strong>Informazioni</strong> sull'articolo</span></h4>
						<%= form_for(@announcement) do |f| %>
              <% if @announcement.errors.any? %>
                <div id="error_explanation">
                <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
                <ul>
                <% @announcement.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
              <% end %>
							<input type="hidden" name="next" value="/">
							<fieldset>
								<div class="control-group">
									<label class="control-label">Titolo</label>
									<div class="controls">
										<%= f.text_field :titolo, :required => true, id: "username", class: "input-xlarge"  %>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Categoria</label>
									<div class="controls">
                    <%= f.select :categoria, ['Auto','Accessori auto',
                                  'Moto', 'Accessori moto',
                                  'Attrezzature da lavoro', 'Informatica',
                                  'Fotografia', 'Audio/video',
                                  'Videogiochi', 'Telefonia',
                                  'Mobili', 'Casalinghi',
                                  'Elettrodomestici', 'Abbigliamento',
                                  'Giardinaggio', 'Tutto per bambini',
                                  'Animali', 'Cancelleria',
                                  'Sport', 'Collezionismo'], include_blank: false, class: "form-control", id: "sel1"  %>
									</div>
								</div>
								<div class="control-group">
              
                
                 <label class="control-label">Foto</label>
                <div class="btn btn-inverse input-group">
                  <label class="input-group-btn ">
                    <span>
                        Scegli la foto <%= f.file_field :foto, accept: 'image/png,image/gif,image/jpeg', style: "display: none;" %>
                    </span>
                  </label>
                  <input type="text" class="form-control" readonly>
                </div> 
								


								</div>
								<div class="control-group">
									<label class="control-label">Luogo</label>
									<div class="controls">
									  <%= f.text_field :luogo, :required => true, class: "input-xlarge" %>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Descrizione</label>
									<div class="controls">
									  <%= f.text_area :descrizione, :rows => 6, style: 'width:90%;', class: "input-xlarge", :required => true %>
									</div>
								</div>
											
					</div>
					<div class="span6">					
						<h4 class="title"><span class="text"><strong>Mappa</strong></span></h4>
					  <table height="100%" width="100%" class="controlss">
              <td valign="top" id="map" ><%= image_tag("map-loader.gif") %></td>
            </table>
					</div>				
				</div>
				<div class="row">
				  <div class="span12">
				    <center>
				      <div class="control-group">
								<%= f.submit "Crea", tabindex:"3", class: "btn btn-inverse large"%> || <%= button_tag "Reset", type: :reset, tabindex:"3", class: "btn btn-inverse large" %>
								</div>
							</fieldset>
						<% end %>
				    </center>
				  </div>
				</div>
			</section>
			
			
<script>
      function initMap() {
        //Posizione di default della mappa
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 41.8919, lng: 12.5113},
          zoom: 13
        });
        
        //Campo di input
        var input = document.getElementById('announcement_luogo');

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            return;
          }

          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }

          // Imposto la posizione sulla mappa della destinazione cercata
          marker.setPlace({
            placeId: place.place_id,
            location: place.geometry.location
          });
          marker.setVisible(true);

          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.formatted_address);
          document.getElementById('announcement_luogo').value = place.formatted_address;
          infowindow.open(map, marker);
        });
      }
    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBIKW0xq45fu2dqUZtBMqXps0SrSHJu0c&libraries=places&callback=initMap"async defer></script>

<script>
  $(function() {

  // We can attach the `fileselect` event to all file inputs on the page
  $(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  // We can watch for our custom `fileselect` event like this
  $(document).ready( function() {
      $(':file').on('fileselect', function(event, numFiles, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
  });
  
});
</script>