config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :feedbacks
  resources :announcements
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations      => "users/registrations",
                                       :sessions           => "users/sessions",
                                       :passwords         => "users/passwords",
                                       :admins            => "users/admins"
                                      }
  

  get "/regolamento", to: "home#regolamento"
  
  root 'home#presentazione'
  get '/profilo', to: 'home#profilo_utente'
  get '/cerca' => 'home#risultati_ricerca'
  get '/cerca_categorie', to: 'home#risultati_ricerca_categorie'
  get '/richieste_inviate', to: 'bookings#richieste_inviate'
  get '/chiudi_richiesta', to: 'bookings#chiudi_annuncio'
  get '/messaggi_inviati', to: 'messages#messaggi_inviati'
  get '/segnala_annuncio', to: 'announcements#segnala_annuncio'
  get '/miostorico',to: 'announcements#storico_oggetti_regalati'
  
  
  
  
  get "/listaUtenti", to: 'users/admins#listaUtenti'
  get "/listaAnnunci", to: 'users/admins#listaAnnunci'
  get "/faiAdmin", to: 'users/admins#faiAdmin'
  get "/modificaUtente_show", to: 'users/admins#modificaUtente_show'
  post "/modificaUtente_update", to: 'users/admins#modificaUtente_update'
  get "/annunciSegnalati", to: 'users/admins#annunciSegnalati'
  get "/togliSegnalato", to: 'users/admins#togliSegnalato'
  get "/modificaAnnuncio_show", to: 'users/admins#modificaAnnuncio_show'
  post "/modificaAnnuncio_update", to: 'users/admins#modificaAnnuncio_update'
  get "/chiudiAnnuncio", to: 'users/admins#chiudiAnnuncio'
  get "/apriAnnuncio", to: 'users/admins#apriAnnuncio'
  get "/listaPrenotazioni", to: "users/admins#listaPrenotazioni"
  
  get "/banna_show", to: "users/admins#banna_show"
  post "/banna_action", to: "users/admins#banna_action"
  get "/togliBan", to: "users/admins#togliBan"
  get "/errori", to: 'home#errori'
  
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :annuncement
  belongs_to :proprietario
  belongs_to :prenotato
  
  
  def nome_proprietario
    User.where("id = ?",proprietario_id).take.nome
  end
  
  def nome_prenotato
    @user = User.where("id = ?",prenotato_id).take
    if @user != nil
      @user.nome
    end
  end
  
  def titolo_annuncio
    @announcemet = Announcement.where("id = ?",annuncio_id).take
    if @announcemet != nil
      @announcemet.titolo
    end
  end
  
  def foto_annuncio
    @announcemet = Announcement.where("id = ?",annuncio_id).take
    if @announcemet != nil
      @announcemet.foto
    end
  end
  
  def etichetta_annuncio
    @announcemet = Announcement.where("id = ?",annuncio_id).take
    if @announcemet != nil
      @announcemet.etichetta
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_filter :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index #i tuoi annunci richiesti
    @bookings = Booking.where("proprietario_id = ?",current_user).order(created_at: :desc)
    @messages = Message.where("mittente_id = ? and destinatario_id = ? ", -1, current_user.id).update_all("stato = 1")
  end
  
  def richieste_inviate
        @bookings = Booking.where("prenotato_id = ?",current_user).order(created_at: :desc)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    Rails.logger.debug "========================================================="
    Rails.logger.debug "#{booking_params}"
    Rails.logger.debug "========================================================="
    @booking = Booking.new(booking_params)
    Announcement.where("id = ?",params[:booking][:annuncio_id]).limit(1).update_all("etichetta = 1") # => 1
    @message = Message.new({"titolo"=>"#{@booking.titolo_annuncio}",
                              "testo"=>"L'utente #{@booking.nome_prenotato} si è prenotato all'annuncio #{@booking.titolo_annuncio}!!",
                              "mittente_id"=>"-1",
                              "destinatario_id"=>"#{@booking.proprietario_id}",
                              "stato"=>"0"})
    respond_to do |format|
      if @booking.save
        @message.save
        format.html { redirect_to richieste_inviate_path, notice: 'Prenotazione avvenuta con successo!' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    Announcement.where("id = ?",@booking.annuncio_id).limit(1).update_all("etichetta = 0") # => 1
    respond_to do |format|
      format.html { redirect_to richieste_inviate_path, notice: 'Prenotazione eliminata con successo!' }
      format.json { head :no_content }
    end
  end
  def chiudi_annuncio
    @booking = Booking.find(params[:id])
    Announcement.where("id = ?",@booking.annuncio_id).limit(1).update_all("etichetta = 2") # => 1
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Transazione annuncio chiusa!' }
      format.json { head :no_content }
    end
  end
   
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:annuncio_id, :proprietario_id, :prenotato_id)
    end
    
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :annuncio_id %><br>
    <%= f.text_field :annuncio_id %>
  </div>
  <div class="field">
    <%= f.label :proprietario_id %><br>
    <%= f.text_field :proprietario_id %>
  </div>
  <div class="field">
    <%= f.label :prenotato_id %><br>
    <%= f.text_field :prenotato_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<center>
	<div class="page-header">
		<h1>I tuoi annunci richiesti</h1>
  </div>
  <% if notice %>
		<div class="alert alert-success">
			<strong><%= notice %></strong>
		</div>
	<% end %>
</center>	

<section class="main-content">				
	<div class="row">
		<div class="span12">
		  <div class="table-responsive">					
			  <table class="table table-striped">
				<thead>
					<tr>
						<th>Foto</th>
						<th>Titolo</th>
						<th>Utente prenotato</th>
						<th>Prenotazione del</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
					<tbody>
					  <% @bookings.each do |booking| %>
						<tr>
							<td><%= link_to image_tag(booking.foto_annuncio, width: "200", height:220), announcement_path(booking.annuncio_id), "data-turbolinks" =>"false"%></a></td>
							<td><%= booking.titolo_annuncio %></td>
							<td><%= link_to booking.nome_prenotato, "/feedbacks?utente=#{booking.proprietario_id}", "data-turbolinks" =>"false"  %></td>
							<td><%= booking.created_at %></td>
							<td><%=  link_to 'Messaggia', "/messages/new?destinatario_id=#{booking.proprietario_id}", "data-turbolinks" =>"false"  %></td>
							
							<% if( booking.etichetta_annuncio == 1) %>
                <td><%= link_to 'Elimina prenotazione', booking, method: :delete, data: { confirm: 'Sei sicuro?' }, "data-turbolinks" =>"false"  %></td>
                <td><%=  link_to 'Chiudi', "/chiudi_richiesta?id=#{booking.id}", "data-turbolinks" =>"false"  %>
              <% else %>
                <td colspan="2">&nbsp;</td>
              <% end %>
						</tr>
						<% end %>
					  <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>		  
					</tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/richieste_inviate.html.erb
 <center><div class="page-header">
        	<h1>Annunci da te richiesti</h1>
      	</div></center>	

  
	<% if notice != nil %>
		<div class="alert alert-success">
		<strong><%= notice %></strong>
	  </div>
  <%end%>
</section>
<section class="main-content">				
	<div class="row">
		<div class="span12">
		  <div class="table-responsive">					
			  <table class="table table-striped">
				<thead>
					<tr>
						<th>Foto</th>
						<th>Titolo</th>
						<th>Proprietario annuncio</th>
						<th>Prenotazione del</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
					<tbody>
					  <% @bookings.each do |booking| %>
						<tr>
							<td><%= link_to image_tag(booking.foto_annuncio, width: "200", height:220), announcement_path(booking.annuncio_id), "data-turbolinks" =>"false"%></a></td>
							<td><%= booking.titolo_annuncio %></td>
							<td><%= link_to booking.nome_proprietario, "/feedbacks?utente=#{booking.proprietario_id}", "data-turbolinks" =>"false"  %></td>
							<td><%= booking.created_at %></td>
							<td><%=  link_to 'Messaggia', "/messages/new?destinatario_id=#{booking.proprietario_id}" %></td>
							
							<% if( booking.etichetta_annuncio == 1) %>
                <td><%= link_to 'Elimina prenotazione', booking, method: :delete, data: { confirm: 'Sei sicuro?' }, "data-turbolinks" =>"false"  %></td>
              <% else %>
                <td colspan="2"><%=  link_to 'Lascia feedback', "/feedbacks/new?utente=#{booking.proprietario_id}&annuncio=#{booking.annuncio_id}&booking=#{booking.id}", "data-turbolinks" =>"false"  %></td>
              <% end %>
							
						</tr>
						<% end %>
					  <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>		  
					</tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/bookings/show.html.erb
<section class="header_text">
	<% if notice != nil %>
		<div class="alert alert-success">
		<strong><%= notice %></strong>
	  </div>
  <%end%>
</section>

<p>
  <strong>Annuncio:</strong>
  <%= @booking.annuncio_id %>
</p>

<p>
  <strong>Proprietario:</strong>
  <%= @booking.proprietario_id %>
</p>

<p>
  <strong>Prenotato:</strong>
  <%= @booking.prenotato_id %>
</p>

<%= link_to 'Back', bookings_path %>