config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :feedbacks
  resources :announcements
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations      => "users/registrations",
                                       :sessions           => "users/sessions",
                                       :passwords         => "users/passwords",
                                       :admins            => "users/admins"
                                      }
  

  get "/regolamento", to: "home#regolamento"
  
  root 'home#presentazione'
  get '/profilo', to: 'home#profilo_utente'
  get '/cerca' => 'home#risultati_ricerca'
  get '/cerca_categorie', to: 'home#risultati_ricerca_categorie'
  get '/richieste_inviate', to: 'bookings#richieste_inviate'
  get '/chiudi_richiesta', to: 'bookings#chiudi_annuncio'
  get '/messaggi_inviati', to: 'messages#messaggi_inviati'
  get '/segnala_annuncio', to: 'announcements#segnala_annuncio'
  get '/miostorico',to: 'announcements#storico_oggetti_regalati'
  
  
  
  
  get "/listaUtenti", to: 'users/admins#listaUtenti'
  get "/listaAnnunci", to: 'users/admins#listaAnnunci'
  get "/faiAdmin", to: 'users/admins#faiAdmin'
  get "/modificaUtente_show", to: 'users/admins#modificaUtente_show'
  post "/modificaUtente_update", to: 'users/admins#modificaUtente_update'
  get "/annunciSegnalati", to: 'users/admins#annunciSegnalati'
  get "/togliSegnalato", to: 'users/admins#togliSegnalato'
  get "/modificaAnnuncio_show", to: 'users/admins#modificaAnnuncio_show'
  post "/modificaAnnuncio_update", to: 'users/admins#modificaAnnuncio_update'
  get "/chiudiAnnuncio", to: 'users/admins#chiudiAnnuncio'
  get "/apriAnnuncio", to: 'users/admins#apriAnnuncio'
  get "/listaPrenotazioni", to: "users/admins#listaPrenotazioni"
  
  get "/banna_show", to: "users/admins#banna_show"
  post "/banna_action", to: "users/admins#banna_action"
  get "/togliBan", to: "users/admins#togliBan"
  get "/errori", to: 'home#errori'
  
end

app/views/layouts/application.html.erb
<html>

<head>
  <title>SmartBucket</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'css_personalizzato', media: 'all', 'data-turbolinks-track' => false %>
    <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => false %>
      <%= stylesheet_link_tag    'bootstrap-responsive.min', media: 'all', 'data-turbolinks-track' => false %>
        <%= stylesheet_link_tag    'themes/css/bootstrappage', media: 'all', 'data-turbolinks-track' => false %>
        
        
        
          <%= stylesheet_link_tag    'themes/css/flexslider', media: 'all', 'data-turbolinks-track' => false %>
            <%= stylesheet_link_tag    'themes/css/main', media: 'all', 'data-turbolinks-track' => false %>

              <%= javascript_include_tag 'themes/js/jquery-1.7.2.min', 'data-turbolinks-track' => false %>
                <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => false %>
                  <%= javascript_include_tag 'themes/js/superfish', 'data-turbolinks-track' => false %>
                    <%= javascript_include_tag 'themes/js/jquery.scrolltotop', 'data-turbolinks-track' => false %>
                    <%= javascript_include_tag "application" %>
                      <%= csrf_meta_tags %>

<style type="text/css">
#STAR_RATING ul
{
  margin: 0px;
  padding: 0px;
  height: 16px;
  list-style: none;
}
#STAR_RATING li
{
  width: 19px;
  height: 16px;
  display: block;
  float: left;
  background-image: url('<%= image_url("star-off.gif") %>');
  background-repeat: no-repeat;
  cursor: pointer;
}
#STAR_RATING li.on
{
  background-image: url('<%= image_url("star-on.gif") %>');
}
#STAR_RATING span.output
{
  padding: 3px;
  color: #339900;
  font-weight: bold;
}
</style>
                      
<% if @feedback %>
  <script type="text/javascript">
  // faccio il preload dell'immagine utilizzata per l'effetto rollover
  var staron = new Image(); staron.src = "<%= image_path("star-on.gif") %>";
  
  // Definisco la funzione per la votazione che verrà lanciata
  // all'evento onclick su una delle 5 stelle
  function star_vota(QT)
  {
    // Creo una variabile con l'output da restituire al momento del voto
    var star_output = '<span class="output">Hai votato ' + QT + ' stelle!</span>';
    // Cambio dinamicamente il contenuto del DIV contenitore con il messaggio di
    // conferma di votazione avvenuta
    document.getElementById('STAR_RATING').innerHTML = star_output;
    
    $.post("/feedbacks",
    {
      utf8: "✓",
      authenticity_token: "<%= form_authenticity_token %>",
      feedback: {
        voto: QT,
        proprietario_id: <%= params[:utente] %>,
        annuncio_id: <%= params[:annuncio] %>,
        booking_id: <%= params[:booking] %>
      }
    },
    function(data,status){
      
    });
  }
  
  // Definisco la funzione per "accendere" dinamicamente le stelle
  // unico argomento è il numero di stelle da accendere
  function star_accendi(QT)
  {
    // verifico che esistano i DIV delle stelle
    // se il DIV non esiste significa che si è già votato
    if (document.getElementById('star_1'))
    {
      // Ciclo tutte e 5 i DIV contenenti le stelle
      for (i=1; i<=5; i++)
      {
        // se il div è minore o uguale del numero di stelle da accendere
        // imposto dinamicamente la classe su "on"
        if (i<=QT) document.getElementById('star_' + i).className = 'on';
        // in caso contrario spengo la stella...
        else document.getElementById('star_' + i).className = '';
      }
    }
  }
  
  // Questa è la funzione che produce l'output.
  // richiede come unico argomento il numero di stelle che si vuole accendere
  // di default (possiamo in questo, ad esempio, modo mostrare il voto ottenuto
  // nelle precedenti votazioni)
  function star(QT)
  {
    // stampo il codice HTML che produce le stelle
    document.write('<div id="STAR_RATING" onmouseout="star_accendi(' + QT + ')""><ul>');
    document.write('<li id="star_1" onclick="star_vota(1)" onmouseover="star_accendi(0); star_accendi(1)"></li>');
    document.write('<li id="star_2" onclick="star_vota(2)" onmouseover="star_accendi(0); star_accendi(2)"></li>');
    document.write('<li id="star_3" onclick="star_vota(3)" onmouseover="star_accendi(0); star_accendi(3)"></li>');
    document.write('<li id="star_4" onclick="star_vota(4)" onmouseover="star_accendi(0); star_accendi(4)"></li>');
    document.write('<li id="star_5" onclick="star_vota(5)" onmouseover="star_accendi(0); star_accendi(5)"></li>');
    document.write('</ul></div>');
    // accendo le stelle definite in argomento
    star_accendi(QT);
  }
  </script>
<%end%>
</head>
<body>
  <script> history.pushState('', '', 'https://smartbucket-maxco93.c9users.io/');</script>	
  <div id="top-bar" class="container">
    <div class="row">
      <div class="span4">
      </div>
      <div class="span8">
        <div class="account pull-right">
          <ul class="user-menu">
            <% if user_signed_in? %>
              <li>
                <%= link_to "#{current_user.email}", edit_user_registration_path, "data-turbolinks" =>"false" %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path, :method => :delete, "data-turbolinks" =>"false"%>
              </li>
              <% else %>
                <li>
                  <%= link_to "Registrati", new_user_registration_path, "data-turbolinks" =>"false" %>
                </li>
                <li>
                  <%= link_to "Login", new_user_session_path %>
                </li>
                <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="wrapper" class="container">
    <section class="navbar main-menu">
      <div class="navbar-inner main-menu">
        <a class="logo pull-left"><%=link_to image_tag("Logo_smartbucket2.png", :border=>0, :class=>"site_logo", "data-turbolinks" =>"false"), root_path,"data-turbolinks" =>"false" %></a>
        <nav id="menu" class="pull-right">
          <ul>
            <% if user_signed_in? %>
              <li>
                <a>Lista annunci</span></a>
                <ul>
                  <li><%= link_to "I tuoi annunci", announcements_path , "data-turbolinks" =>"false" %></li>
                   <li><%= link_to "I tuoi annunci chiusi", miostorico_path , "data-turbolinks" =>"false" %></li>
                </ul>
              </li>
              <li>
                <%= link_to 'Nuovo annuncio', new_announcement_path, "data-turbolinks" =>"false" %>
              </li>
              <li>
                <a>Richieste <span class="label label-default"><% if current_user.conta_nuove_richieste > 0 %>NEW<%end%></span></a>
                <ul>
                  <li><%= link_to "Richieste inviate", "/richieste_inviate", "data-turbolinks" =>"false" %></li>
                  <li><a data-turbolinks="false" href="/bookings">Richieste ricevute  <% if current_user.conta_nuove_richieste >0 %><span class="badge"><%= current_user.conta_nuove_richieste %></span><%end%></a></li>
                </ul>
              </li>
              <li><a>Messaggi <% if current_user.conta_nuovi_messaggi>0 %> <span class="badge"><%= current_user.conta_nuovi_messaggi %></span><%end%></a>
                <ul>
                  <li><%= link_to 'Messaggi ricevuti', messages_path, "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Messaggi inviati', "/messaggi_inviati", "data-turbolinks" =>"false" %></li>
                </ul>
              </li>
              <li>
                <%= link_to 'I miei feedback', "/feedbacks?utente=#{current_user.id}", "data-turbolinks" =>"false" %>
              </li>
              <% if(current_user.tipo_utente == 1) %>
              <li>
                <a>Funzioni admin</span></a>
                <ul>
                  <li><%= link_to 'Lista utenti', "/listaUtenti", "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Lista annunci', "/listaAnnunci", "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Annunci segnalati', "/annunciSegnalati", "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Lista prenotazioni', "/listaPrenotazioni", "data-turbolinks" => "false" %></li>
                </ul>
              </li>
              <% end %>
              <% end %>
          </ul>
        </nav>
      </div>
    </section>



    <%= yield =%>


      <section id="footer-bar">
        <div class="row">
          <div class="span3">
            <h4>Naviga</h4>
            <ul class="nav">
              
              <li><%= link_to "Homepage", root_path, "data-turbolinks" =>"false" %></li>
              <li><a href="/regolamento">Regolamento</a></li>
            </ul>
          </div>
          <div class="span4">
            <% if user_signed_in? %>
              <h4>Il mio account</h4>
              <ul class="nav">
                <li><%= link_to "Il mio account", edit_user_registration_path, "data-turbolinks" =>"false" %></li>
                <li><%= link_to "I tuoi annunci", announcements_path, "data-turbolinks" =>"false" %></li>
                <li><%= link_to "Richieste inviate", "/richieste_inviate", "data-turbolinks" =>"false" %></li>
              </ul>
            <%end%>
          </div>
          <div class="span5">
            <p class="logo">
              <%= image_tag("Logo_smartbucket2.png", :border=>0, :class=>"site_logo") %>
            </p>
            <p>Non sai come liberarti di vecchi oggetti che non usi più? ma che magari sono ancora utili e ti dispiace buttarli?<br/>Non c'è probelma, utilizza il nostro servizio e dona quelle cose a chi ne ha bisogno grazie a smartbucket!!</p>
            <br/>
          </div>
        </div>
      </section>
      
      
      
      <section id="copyright">
        <span>Copyright 2016  All right reserved.</span>
      </section>
  </div>

  <%= javascript_include_tag 'themes/js/common', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'themes/js/jquery.flexslider-min', 'data-turbolinks-track' => false %>
      <script type="text/javascript">
        $(function() {
          $(document).ready(function() {
            $('.flexslider').flexslider({
              animation: "fade",
              slideshowSpeed: 4000,
              animationSpeed: 600,
              controlNav: false,
              directionNav: true,
              controlsContainer: ".flex-container" // the container that holds the flexslider
            });
          });
        });
      </script>
</body>

</html>

app/views/layouts/per_annunci.html.erb
<!DOCTYPE html>
<html lang="en">

<head >


	<%= favicon_link_tag %>
		<%= csrf_meta_tags %>
			<title>SmartBucket</title>
			<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="">


	



			<!-- bootstrap -->
			<%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => false %>
				<%= stylesheet_link_tag    'bootstrap-responsive.min', media: 'all', 'data-turbolinks-track' => false %>
					<%= stylesheet_link_tag    'themes/css/bootstrappage', media: 'all', 'data-turbolinks-track' => false %>
					<%= stylesheet_link_tag    'css_personalizzato', media: 'all', 'data-turbolinks-track' => false %>

						<!-- global styles -->
						<%= stylesheet_link_tag    'themes/css/main', media: 'all', 'data-turbolinks-track' => false %>
							<%= stylesheet_link_tag    'themes/css/jquery.fancybox', media: 'all', 'data-turbolinks-track' => false %>

								<!-- scripts -->
								<%= javascript_include_tag "application" %>
								<%= javascript_include_tag 'themes/js/jquery-1.7.2.min', 'data-turbolinks-track' => false %>
									<%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
										<%= javascript_include_tag 'themes/js/superfish', 'data-turbolinks-track' => true %>
											<%= javascript_include_tag 'themes/js/jquery.scrolltotop', 'data-turbolinks-track' => false %>
												<%= javascript_include_tag 'themes/js/jquery.fancybox', 'data-turbolinks-track' => false %>
</head>
<body>
  <script> history.pushState('', '', 'https://smartbucket-maxco93.c9users.io/');</script>	
  <div id="top-bar" class="container">
    <div class="row">
      <div class="span4">
      </div>
      <div class="span8">
        <div class="account pull-right">
          <ul class="user-menu">
            <% if user_signed_in? %>
              <li>
                <%= link_to "#{current_user.email}", edit_user_registration_path, "data-turbolinks" =>"false" %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path, :method => :delete, "data-turbolinks" =>"false"%>
              </li>
              <% else %>
                <li>
                  <%= link_to "Registrati", new_user_registration_path, "data-turbolinks" =>"false" %>
                </li>
                <li>
                  <%= link_to "Login", new_user_session_path, "data-turbolinks" =>"false" %>
                </li>
                <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="wrapper" class="container">
    <section class="navbar main-menu">
      <div class="navbar-inner main-menu">
        <a class="logo pull-left"><%=link_to image_tag("Logo_smartbucket2.png", :border=>0, :class=>"site_logo", "data-turbolinks" =>"false"), root_path %></a>
        <nav id="menu" class="pull-right">
          <ul>
            <% if user_signed_in? %>
              <li>
                <a>Lista annunci</span></a>
                <ul>
                  <li><%= link_to "I tuoi annunci", announcements_path , "data-turbolinks" =>"false" %></li>
                   <li><%= link_to "I tuoi annunci chiusi", miostorico_path , "data-turbolinks" =>"false" %></li>
                </ul>
              </li>
              <li>
                <%= link_to 'Nuovo annuncio', new_announcement_path, "data-turbolinks" =>"false" %>
              </li>
              <li>
                <a>Richieste <span class="label label-default"><% if current_user.conta_nuove_richieste > 0 %>NEW<%end%></span></a>
                <ul>
                  <li><%= link_to "Richieste inviate", "/richieste_inviate", "data-turbolinks" =>"false" %></li>
                  <li><a data-turbolinks="false" href="/bookings">Richieste ricevute  <% if current_user.conta_nuove_richieste >0 %><span class="badge"><%= current_user.conta_nuove_richieste %></span><%end%></a></li>
                </ul>
              </li>
              <li>
                <a>Messaggi <% if current_user.conta_nuovi_messaggi>0 %> <span class="badge"><%= current_user.conta_nuovi_messaggi %></span><%end%></a>
                <ul>
                  <li><%= link_to 'Messaggi ricevuti', messages_path, "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Messaggi inviati', "/messaggi_inviati", "data-turbolinks" =>"false" %></li>
                </ul>
              </li>
              <li>
                <%= link_to 'I miei feedback', "/feedbacks?utente=#{current_user.id}", "data-turbolinks" =>"false" %>
              </li>
              <% if(current_user.tipo_utente == 1) %>
              <li>
                <a>Funzioni admin</span></a>
                <ul>
                  <li><%= link_to 'Lista utenti', "/listaUtenti", "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Lista annunci', "/listaAnnunci", "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Annunci segnalati', "/annunciSegnalati", "data-turbolinks" =>"false" %></li>
                  <li><%= link_to 'Lista prenotazioni', "/listaPrenotazioni", "data-turbolinks" => "false" %></li>
                </ul>
              </li>
              <% end %>
              <% else %>
                <li><a>FAQ</a></li>
              <% end %>
          </ul>
        </nav>
      </div>
    </section>


<%= yield =%>

      <section id="footer-bar">
        <div class="row">
          <div class="span3">
            <h4>Naviga</h4>
            <ul class="nav">
              
              <li><%= link_to "Homepage", root_path, "data-turbolinks" =>"false" %></li>
              <li><a href="/regolamento">Regolamento</a></li>
            </ul>
          </div>
          <div class="span4">
            <% if user_signed_in? %>
              <h4>Il mio account</h4>
              <ul class="nav">
                <li><%= link_to "Il mio account", edit_user_registration_path, "data-turbolinks" =>"false" %></li>
                <li><%= link_to "I tuoi annunci", announcements_path, "data-turbolinks" =>"false" %></li>
                <li><%= link_to "Richieste inviate", "/richieste_inviate", "data-turbolinks" =>"false" %></li>
              </ul>
            <%end%>
          </div>
          <div class="span5">
            <p class="logo">
              <%= image_tag("Logo_smartbucket2.png", :border=>0, :class=>"site_logo") %>
            </p>
            <p>Non sai come liberarti di vecchi oggetti che non usi più? ma che magari sono ancora utili e ti dispiace buttarli?<br/>Non c'è probelma, utilizza il nostro servizio e dona quelle cose a chi ne ha bisogno grazie a smartbucket!!</p>
            <br/>
          </div>
        </div>
      </section>
      <section id="copyright">
        <span>Copyright 2016  All right reserved.</span>
      </section>
		</div>
  <%= javascript_include_tag 'themes/js/common', 'data-turbolinks-track' => false %>
		<script>
			$(document).ready(function() {
				$('#checkout').click(function (e) {
					document.location.href = "checkout.html";
				})
			});
		</script>	
    </body>
</html>